### PR TITLE
Initial version

### PR DESCRIPTION
**Pull request by nicorusti**
This change is [Reviewable](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1)

- [x] Start with a section describing the properties we think a good global Internetwork must contain: security, scalability, availability in case of failure, transparency, multi-path/flexibility, end-host control... Then that SCION was developed to meet these property requirements.
- [x] Discussion of each property for each core component (I am not sure about the structure: whether to take the core components as upper level, and the properties as the lower level, or the other way around).
For each property: how SCION achieves this property, in relation to the existing Internet. I think you can re-use all property content you already wrote, this is more a matter of re-organizing the content.=
- [x] Related work section: RPKI,  BGPSec, Semantic Routing (Add)
We should make it clear: what protocols are we reusing, which ones are we extending, which ones are we replacing and not reusing …. We should explain clearly why we are not reusing existing protocols.
- [x] Conclude with dependency analysis, which explains very nicely that the core components cannot really exist on their own (except maybe for the CP-PKI). 
- [ ] Transition mechanism & additional components: remove or rework

General feedback: 
- [ ] Make it more clear why we do not reuse existing protocols
- [ ]  RFC9049: use it as a filter for our ideas. Explain why SCION considers lessons learned
- [x] Use RFC 7418  to explain and motivate what should go into IETF and what should go into IRTF --> I guess this will pop up in discussions. Some we are roughly at half and half, and some of the work should be IETF. I think this should not be in the draft.

### CODE REVIEW

**Review by cdekater — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cdekater and @nicorusti)

___
*[`draft-rustignoli-panrg-scion-components.md` line 280 at r1](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1#-N5nmIWZ-ERS-xKupTJY:-N5nmIWZ-ERS-xKupTJZ:bc7qy2z) ([raw file](https://github.com/scionassociation/scion-components_i-d/blob/3da4ef9ab5b944b7f35383bf93eaa6bf76992d77/draft-rustignoli-panrg-scion-components.md#L280)):*
> ```Markdown
> 
> While SCION  was initially developed in academia, the architecture  has now "slipped out of the lab" and counts its early productive deployments (including the Swiss inter-banking network SSFN).
> The architecture consists of a system of related components, some of which are  essential to set up end to end SCION connectivity, while others are add-ons aiming at providing additional functionality, security, or backwards compatibility. Discussions at {{PANRG-INTERIM-Min}} showed the need to describe the relationships between SCION's core components.
> ```

I am not sure whether the PANRG people wanted to know more about the relationship between SCION's core components. My impression was that they wanted to know (1) what is the minimal SCION stack needed to make SCION work, and (2) the relationship between SCION and existing protocols. More precisely: Which existing protocols does SCION use, which not, and why not.
  
___
*[`draft-rustignoli-panrg-scion-components.md` line 303 at r1](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1#-N5noIv5A2tYwt1L_hNA:-N5noIv5A2tYwt1L_hNB:b-2js1rb) ([raw file](https://github.com/scionassociation/scion-components_i-d/blob/3da4ef9ab5b944b7f35383bf93eaa6bf76992d77/draft-rustignoli-panrg-scion-components.md#L303)):*
> ```Markdown
> ISD members share an uniform trust environment (i.e., a common jurisdiction).
> They can transparently define trust relationships between parts of the network by deciding wether to trust other ISDs.
> SCION therefore relies on an unique trust model, which is markably different from other PKI. We clarify the motivation behind this in [Authentication](#pki)
> ```

Maybe not use the word "markably"? Different is enough.
___
*[`draft-rustignoli-panrg-scion-components.md` line 316 at r1](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1#-N5nrjzE98mm_k5BfYoc:-N5nrjzFAJT9hOE4QS8b:bv1muc7) ([raw file](https://github.com/scionassociation/scion-components_i-d/blob/3da4ef9ab5b944b7f35383bf93eaa6bf76992d77/draft-rustignoli-panrg-scion-components.md#L316)):*
> ```Markdown
> 
> ### Key properties in relationship to existing protocols
> On a first sight, it might seem that SCION control plane takes care of similar duties as of BGP. While both focus on disseminating routing information, there are substantial differences in the properties provided and mechanisms. We describe the core properties provided by the SCION control plane, and its relationships with existing protocols.
> ```

I think the properties approach is good. But maybe we should first describe why these properties are important in general, something like that we think a "good" Internet needs to include these properties, that SCION tries to address/meet these properties, and that SCION may therefore differ from existing protocols in those cases where the existing protocols are not able to sufficiently meet the properties.

**Review by nicorusti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cdekater and @nicorusti)

___
*[`draft-rustignoli-panrg-scion-components.md` line 280 at r1](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1#-N5nmIWZ-ERS-xKupTJY:-N5nwGcq1GAN5IY3AyhF:b-opfcx8) ([raw file](https://github.com/scionassociation/scion-components_i-d/blob/3da4ef9ab5b944b7f35383bf93eaa6bf76992d77/draft-rustignoli-panrg-scion-components.md#L280)):*
> I am not sure whether the PANRG people wanted to know more about the relationship between SCION's core components. My impression was that they wanted to know (1) what is the minimal SCION stack needed to make SCION work, and (2) the relationship between SCION and existing protocols. More precisely: Which existing protocols does SCION use, which not, and why not.

But there was a lot of discussion about splitting components, which is not a good idea. THis is why I want to stress that the 3 core components are quite tightly interlinked.

**Review by cdekater — COMMENTED** [review]
Hi Nicola,

I like your draft, it already contains a lot of really good content, and I also like your style of writing very much! 

As we already discussed, I would just restructure it a bit:
1. Start with a section describing the properties we think a good global Internetwork must contain: security, scalability, availability in case of failure, transparency, multi-path/flexibility, end-host control...
2. Then that SCION was developed  to meet these property requirements.
3. Description of SCION minimal stack (this content is already there).
4. Discussion of each property for each core component (I am not sure about the structure: whether to take the core components as upper level, and the properties as the lower level, or the other way around).
-   For each property: how SCION achieves this property, in relation to the existing Internet. I think you can re-use all property content you already wrote, this is more a matter of re-organizing the content. 
5. I like the sections about SCION and Segment Routing/RPKI. I would add these sections after the above discussion, under "Related work" or something alike. Maybe also add sections on Semantic Routing/BGPsec?
6.  You could finish the draft with the dependency analysis, which explains very nicely that the core components cannot really exist on their own (except maybe for the CP-PKI).
7. I am not sure about the sections Transition Mechanisms and Additional Components. Regarding the Transition Mechanisms, I would either only mention SIG, or refer to "my" draft entirely. And I would not mention the additional components at all. I think the draft has already enough content without it 

> *[Reviewable](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1#-:-N5onJUXBj-AyVGS0egU:b-2n815r)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cdekater and @nicorusti)

___
*[`draft-rustignoli-panrg-scion-components.md` line 280 at r1](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1#-N5nmIWZ-ERS-xKupTJY:-N5okjWd8ePW9ibqFaSH:b-c3tnvp) ([raw file](https://github.com/scionassociation/scion-components_i-d/blob/3da4ef9ab5b944b7f35383bf93eaa6bf76992d77/draft-rustignoli-panrg-scion-components.md#L280)):*
<details><summary><i>Previously, nicorusti (Nicola Rustignoli) wrote…</i></summary><blockquote>

> I am not sure whether the PANRG people wanted to know more about the relationship between SCION's core components. My impression was that they wanted to know (1) what is the minimal SCION stack needed to make SCION work, and (2) the relationship between SCION and existing protocols. More precisely: Which existing protocols does SCION use, which not, and why not.

But there was a lot of discussion about splitting components, which is not a good idea. THis is why I want to stress that the 3 core components are quite tightly interlinked. 
 

</blockquote></details>

Good point!

**Review by cdekater — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1)* status: all files reviewed, 3 unresolved discussions (waiting on @nicorusti)

**Review by nicorusti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cdekater and @nicorusti)

___
*[`draft-rustignoli-panrg-scion-components.md` line 303 at r1](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1#-N5noIv5A2tYwt1L_hNA:-N5u3sbD83iWHbE6n6af:b-896fix) ([raw file](https://github.com/scionassociation/scion-components_i-d/blob/3da4ef9ab5b944b7f35383bf93eaa6bf76992d77/draft-rustignoli-panrg-scion-components.md#L303)):*
<details><summary><i>Previously, cdekater wrote…</i></summary><blockquote>

Maybe not use the word "markably"? Different is enough.
</blockquote></details>

Done.
___
*[`draft-rustignoli-panrg-scion-components.md` line 320 at r2](https://reviewable.io/reviews/scionassociation/scion-components_i-d/1#-N5uj24z5x17ziRhE5Xh:-N5uj25-1-6RvtPfA2qH:b-vi1x04) ([raw file](https://github.com/scionassociation/scion-components_i-d/blob/ba4d14d59292aee7199f2dace77cb5acba460c2d/draft-rustignoli-panrg-scion-components.md#L320)):*
> ```Markdown
> 
> ```

@cdekater I added this section. Besides that, I could add even more. Something like: 
```
There are many use cases where existing protocols show the limitations of existing inter-domain routing approaches: 
- Cloud to customer connectivity:  
- Enterprise communication: 
- ... 
```

But I'd update the other draft (where we already have a motivation paragraph), rather than having a "duplicate" motivation paragraph here. Thoughts?  



_Code quote:_
```Markdown
## Design goals
SCION was created from inception with the intention of providing the following properties for inter-domain communication.

- *Availability*. SCION is meant to provide highly available communication. The focus is not only on handling failures (both on the last hop or anywhere along the path), but also on allowing communication in presence of adversaries.
Availability is fundamental as applications move to cloud datacenters and enterprises increasingly rely on Internet communication for mission-critical communication.

- *Security*. SCION was designed by security researchers with the goal of making most network-based and routing attacks either impossible or easy to mitigate.
Security means also offering end-hosts transparency and control over forwarding paths. In addition, SCION's design starts from the assumption that any two entities on the global Internet do not mutually trust each other.
SCION therefore enables trust agility, allowing users to decide the roots of trust they wish to rely upon.

- *Scalability*.  Security and high availability should not result in compromises on scalability.
The S in SCION, indeed, stands for scalability.
The goal is to achieve routing that scales with network growth, both in the control plane and in the data plane (forwarding should be as efficient as possible).
```

**Pull request merged**
